<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="gbibc-dv00-17-v" name="com.ics.tests.ia.ColumnName" tests="1" failures="1" timestamp="28 Feb 2017 09:42:39 GMT" time="94.327" errors="0">
  <testcase name="TC69707" time="94.327" classname="com.ics.tests.ia.ColumnName">
    <failure type="java.lang.AssertionError" message="true expected [STO] but found []">
      <![CDATA[java.lang.AssertionError: true expected [STO] but found []
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at com.ics.seleniumCoreUtilis.Component.assertEquals(Component.java:108)
	at com.ics.ia.pages.iaSearchResultsPage.ValidateLabel_OP_STO(iaSearchResultsPage.java:280)
	at com.ics.ia.pages.testScenarios.SearchItemResultFlow.run(SearchItemResultFlow.java:40)
	at com.ics.ia.pages.testScenarios.SearchItemResultFlow.run(SearchItemResultFlow.java:1)
	at com.ics.seleniumCoreUtilis.Component.run(Component.java:150)
	at com.ics.tests.ia.ColumnName.TC69707(ColumnName.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC69707 -->
</testsuite> <!-- com.ics.tests.ia.ColumnName -->
